### ISSUE TITLE
Unable to import whispers scan to Defect Dojo

### ISSUE THREAD

**Issue by BestChinchilla** [adeptex/whispers#100]
**Describe the bug**
When trying to import scan results in JSON format from Defect Dojo web interface, an error appears:
```An exception error occurred during the report import:Tried to update field dojo.Finding.references with a model instance, <Endpoint: https://cwe.mitre.org/data/definitions/798.html>. Use a value compatible with TextField.```

**To Reproduce**
1. Using input:
```
# Compliant
username: hardcoded
environment:
  - DB_USER=hardcoded
MasterUserPassword: !Ref 'MasterUserPassword'
db_password: "null"
creds: DB_PASSWORD=set=it=here
passphrase: ''

# Noncompliant
pwd: hardcoded1
passwd: hardcoded2
invar: DB_PASSWORD=hardcoded3
inlist:
  - DB_PASSWORD=hardcoded4
passphrase: hardcoded5
```
2. Run like this:
```whispers ./passwords.yml -o /tmp/secrets.json --xrules file-known```
3. Get JSON file and try to import it to Defect Dojo engagement
4. See error in web interface

**Expected behavior**
Succesfully imported whispers report

**Screenshots**
![image](https://github.com/adeptex/whispers/assets/65246628/9a6cbf1d-e7ff-4379-b06c-bf1ef4760333)

**System information:**
 - OS (name, version): Ubuntu 20.04.6 LTS
 - Docker image: python:3.9-slim
 - Python version: python:3.9
 - Whispers version: 2.1.5
 - Defect Dojo version: 2.22.3

**Additional context**
Stacktrace in Defect Dojo:
```
[30/Jun/2023 22:59:32] ERROR [dojo.engagement.views:703] Tried to update field dojo.Finding.references with a model instance, <Endpoint: https://cwe.mitre.org/data/definitions/798.html>. Use a value compatible with TextField.
Traceback (most recent call last):
  File "/app/dojo/engagement/views.py", line 687, in import_scan_results
    test, finding_count, closed_finding_count, _ = importer.import_scan(scan, scan_type, engagement, user, environment, active=active, verified=verified, tags=tags,
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/importer/importer.py", line 337, in import_scan
    new_findings = self.process_parsed_findings(test, parsed_findings, scan_type, user, active=active,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/decorators.py", line 47, in __wrapper__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 392, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/importers/importer/importer.py", line 160, in process_parsed_findings
    item.save(push_to_jira=push_to_jira)
  File "/app/dojo/models.py", line 2782, in save
    super(Finding, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 976, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1040, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1216, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1385, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1782, in as_sql
    raise TypeError(
TypeError: Tried to update field dojo.Finding.references with a model instance, <Endpoint: https://cwe.mitre.org/data/definitions/798.html>. Use a value compatible with TextField.
```

**Comment by adeptex** [comment]
hey @BestChinchilla, thanks for reaching out! Let me have a look at this one.....

**Comment by adeptex** [comment]
@BestChinchilla this should be resolved now. Please open another issue if it's not. Once again, thanks very much for raising this! 

Cheers
