### ISSUE TITLE
Whispers command not returning shell exit code when there are errors

### ISSUE THREAD

**Issue by evanharmon1** [adeptex/whispers#105]
**Describe the bug**
My understanding is that the whispers command should return a shell exit code in certain situations in order to signal certain issues with the code, but I can't get that behavior working.

Using the -e switch to specify exit codes only seems to force an exit code, rather than return an exit code only when there are errors.

**To Reproduce**
1. `whispers --severity BLOCKER,CRITICAL .` or `whispers .`
Returns various warnings, errors, critical issues in both the terminal output and in the json output at the end but the whispers command does not return an exit code to the terminal.

**Expected behavior**
I expected whispers to return an exit code in order to block CI tools and automated tests, etc.

**System information:**
 - OS: macOS Ventura
 - Python version: 3.11.4
 - Whispers version: 2.1.5
 - zsh 5.9 (x86_64-apple-darwin22.0)

**Additional context**
Maybe some of these other errors are affecting something?
```
[WARNING] [osConfig/mac/mackup/myDotFiles.cfg:0] file = osConfig/mac/mackup/myDotFiles.cfg
[ERROR] Failed parsing file 'osConfig/mac/mackup/myDotFiles.cfg' with make_pairs()
Traceback (most recent call last):
  File "/Users/evan/.pyenv/versions/3.11.4/lib/python3.11/site-packages/whispers/core/pairs.py", line 58, in make_pairs
    yield from tagged
  File "/Users/evan/.pyenv/versions/3.11.4/lib/python3.11/site-packages/whispers/plugins/config.py", line 26, in pairs
    yield from self.parse_as_ini(filepath)
  File "/Users/evan/.pyenv/versions/3.11.4/lib/python3.11/site-packages/whispers/plugins/config.py", line 36, in parse_as_ini
    parser.read(filepath.as_posix())
  File "/Users/evan/.pyenv/versions/3.11.4/lib/python3.11/configparser.py", line 713, in read
    self._read(fp, filename)
  File "/Users/evan/.pyenv/versions/3.11.4/lib/python3.11/configparser.py", line 1132, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: 'osConfig/mac/mackup/myDotFiles.cfg'
        [line  7]: '.dotfiles\n'
        [line  8]: '.gitignore_global\n'
[WARNING] [osConfig/git/.gitconfig:0] file = osConfig/git/.gitconfig
[{"key": "file", "value": "infra/MacMini2014/plex/plex.env", "file": "infra/MacMini2014/plex/plex.env", "line": 0, "rule_id": "file-known", "message": "Known file", "severity": "MINOR"}, {"key": "POSTGRES_PASSWORD", "value": "password123", "file": "osConfig/docker/docker-compose-db.yml", "line": 11, "rule_id": "password", "message": "Password", "severity": "CRITICAL"}, {"key": "file", "value": "osConfig/shell/bash/.bashrc", "file": "osConfig/shell/bash/.bashrc", "line": 0, "rule_id": "file-known", "message": "Known file", "severity": "MINOR"}, {"key": "file", "value": "osConfig/shell/.dotfiles/.functions", "file": "osConfig/shell/.dotfiles/.functions", "line": 0, "rule_id": "file-known", "message": "Known file", "severity": "MINOR"}, {"key": "file", "value": "osConfig/shell/zsh/.zshrc", "file": "osConfig/shell/zsh/.zshrc", "line": 0, "rule_id": "file-known", "message": "Known file", "severity": "MINOR"}, {"key": "file", "value": "osConfig/mac/mackup/.mackup.cfg", "file": "osConfig/mac/mackup/.mackup.cfg", "line": 0, "rule_id": "file-known", "message": "Known file", "severity": "MINOR"}, {"key": "file", "value": "osConfig/mac/mackup/myDotFiles.cfg", "file": "osConfig/mac/mackup/myDotFiles.cfg", "line": 0, "rule_id": "file-known", "message": "Known file", "severity": "MINOR"}, {"key": "file", "value": "osConfig/git/.gitconfig", "file": "osConfig/git/.gitconfig", "line": 0, "rule_id": "file-known", "message": "Known file", "severity": "MINOR"}]
```

**Comment by adeptex** [comment]
hey @evanharmon1, thanks for reaching out. This is by design following `whispers --help`:
```
  -e EXITCODE, --exitcode EXITCODE
                        exit code on success
```

Whispers continues to scan even if it fails to parse any given file.
