### ISSUE TITLE
Not-parseable JSON with comment in double-quotes and beginning with spaces

### ISSUE THREAD

**Issue by cosad3s** [adeptex/whispers#127]
**Describe the bug**

When a JSON contains a comment beginning with space, inside double-quotes, then Whispers fails to parse it.

**To Reproduce**

Example of valid JSON for this bug:

```json
{
  "id": "1234",
  "events": [
    {
      "listen": "test",
      "script": {
        "id": "1",
        "exec": [
          "// this is not a real comment too",
          "hello(\"atob\");",
          "",
          "test",
          "test2",
          "",
          "        // this is not a real comment too",
          "bla"
        ],
        "type": "whatever"
      }
    }
  ]
}
```

`whispers ./whisperbug.json`

Error:

```bash
❯ whispers ./whisperbug.json
[ERROR] Failed parsing file './whisperbug.json' with {
  "id": "1234",
  "events": [
    {
      "listen": "test",
      "script": {
        "id": "1",
        "exec": [
          "// this is not a real comment too",
          "hello(\"atob\");",
          "",
          "test",
          "test2",
          "",
          "       
          "bla"
        ],
        "type": "whatever"
      }
    }
}
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.11/site-packages/whispers/plugins/json.py", line 27, in pairs
    document = json.loads(document)
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid control character at: line 15 column 19 (char 277)
[]
```

*As you can see, Whispers creates an invalid line on the 2nd occurence of a comment in double-quotes*

**Expected behavior**

Whispers should parse this JSON.

**System information:**
 - OS (name, version): Kali 6.6.9-amd64
 - Python version: 3.11.8
 - Whispers version: 2.2.0

**Comment by adeptex** [comment]
Hey @cosad3s thanks for raising, I will take a look..
